PROGRAM_1 = mergeSort
SOURCE_1 = mergeSort.cpp
PROGRAM_2 = mergeSortInplace
SOURCE_2 = mergeSortInplace.cpp

all:
	g++ -std=c++11 -o $(PROGRAM_1) $(SOURCE_1)
	g++ -std=c++11 -o $(PROGRAM_2) $(SOURCE_2)

clean:
	rm $(PROGRAM_1) $(PROGRAM_2) 