PROGRAM = Maze
SOURCE = Maze.cpp

all:
	g++ $(SOURCE) -o $(PROGRAM)

clean:
	rm $(PROGRAM) StudentNumber_homework3.zip

handin:
	zip -r StudentNumber_homework3.zip $(SOURCE) Makefile testmap_1.txt testmap_2.txt testmap_3.txt
	echo "Modify StudentNumber to your own"

